[component.mcp-tool]
uri = "../../components/lib/mcp-tool.wasm"
imports = ["mcp-client"]
config.server-url = "http://localhost:3001/mcp"
config.tool-name = "multiply"

[component.mcp-client]
uri = "../../components/lib/mcp-client.wasm"
imports = ["http-client", "logger"]

[component.http-client]
uri = "oci://ghcr.io/modulewise/component/http-client:0.4.0"
imports = ["http"]

[component.logger]
uri = "oci://ghcr.io/componentized/logging/to-stdout:v0.2.1"
imports = ["stdout-to-stderr", "io", "clocks"]

[component.stdout-to-stderr]
uri = "oci://ghcr.io/componentized/cli/stdout-to-stderr:v0.1.1"
imports = ["io", "cli"]

[capability.http]
type = "wasi:http"

[capability.io]
type = "wasi:io-p2"

[capability.clocks]
type = "wasi:clocks-p2"

[capability.cli]
type = "wasi:cli-p2"
inherit-stderr = true
