[component.greeter-tool]
uri = "./lib/tool-adapter.wasm"
imports = ["greeter-function"]
config.description = "Greets someone by name"
config.spec-version = "2026-07-28"

[component.greeter-function]
uri = "factory:greeter-function-factory"
imports = ["target", "mapper"]

[component.target]
uri = "./lib/greeter.wasm"

[component.mapper]
uri = "./lib/json-mapper.wasm"

[component.greeter-function-factory]
uri = "./lib/function-factory.wasm"
imports = ["loader"]
config.target = "/lib/greeter.wasm"

[component.loader]
uri = "./lib/filesystem-loader.wasm"
imports = ["filesystem"]

[capability.filesystem]
type = "wasi:filesystem"

[[capability.filesystem.preopens]]
host = "./lib"
guest = "/lib"
perms = "read-only"
