[component.greeter-tool]
uri = "./lib/tool-adapter.wasm"
imports = ["greeter-function"]
config.description = "Greets someone by name"
config.spec-version = "2026-07-28"

[component.greeter-function]
uri = "factory:greeter-function-factory"
imports = ["target", "mapper"]

[component.target]
uri = "oci://ghcr.io/modulewise/demo/hello:0.2.0"

[component.mapper]
uri = "oci://ghcr.io/modulewise/component/json-mapper:0.4.0"

[component.greeter-function-factory]
uri = "oci://ghcr.io/modulewise/component/function-factory:0.5.0"
config.wit = "${wit(target)}"
